spring.application.name=credit_system
spring.datasource.url=jdbc:mysql://localhost:3306/credit_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=9148
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
server.port=8081
